#!/usr/bin/env bash

# Copyright (C) 2025 Diwas Neupane
# SPDX-License-Identifier: GPL-3.0-only
# Kernel build script

KERNELDIR=$1
if [[ -z ${KERNELDIR} ]]; then
    echo -e "Please set KERNELDIR"
    exit 1
fi

[[ -z ${DEVICE} ]] && DEVICE=dandelion

# These won't change
export SRCDIR="${KERNELDIR}/${DEVICE}"
export OUTDIR="${KERNELDIR}/${DEVICE}/obj"
export ARCH="arm64"
CCACHE="$(command -v ccache)"
export CLANG_DIR="$KERNELDIR/aosp-clang/clang-r353983c"
export CLANG_TRIPLE="aarch64-linux-gnu-"
export CC="${CLANG_DIR}/bin/clang"
KBUILD_COMPILER_STRING=$(${CC} --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')
export GCC_DIR="$KERNELDIR/aarch64-linux-android-4.9"
CROSS_COMPILE="$GCC_DIR/bin/aarch64-linux-android-"
export CROSS_COMPILE_ARM32="${KERNELDIR}/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-"
export DEFCONFIG="${DEVICE}_defconfig"
export IMAGE="${OUTDIR}/arch/${ARCH}/boot/Image.gz"
if [[ -z ${JOBS} ]]; then
    JOBS="$(grep -c '^processor' /proc/cpuinfo)"
fi
export DEVICE CCACHE KBUILD_COMPILER_STRING JOBS CROSS_COMPILE

# create two dummy firmware blobs, it's for dandelion only
mkdir -p "${SRCDIR}/drivers/input/touchscreen/mediatek/ft8006s_spi/include/firmware"
touch "${SRCDIR}/drivers/input/touchscreen/mediatek/ft8006s_spi/include/firmware/fw_helitai_v0e.i"
touch "${SRCDIR}/drivers/input/touchscreen/mediatek/ft8006s_spi/include/firmware/fw_sample.i"

function make_wrapper() {
    time make -j"${JOBS}" \
        O="${OUTDIR}" \
        ARCH="${ARCH}" \
        CC="${CCACHE} ${CC}" \
        CLANG_TRIPLE="${CLANG_TRIPLE}" \
        CROSS_COMPILE="${CROSS_COMPILE}" \
        CROSS_COMPILE_ARM32="${CROSS_COMPILE_ARM32}" \
        HOSTCFLAGS="-fcommon" \
        "${@}"
}

[ ! -d "${OUTDIR}" ] && mkdir -pv "${OUTDIR}"

cd "${SRCDIR}" || exit
rm -fv "${IMAGE}"

if [[ $* =~ "mrproper" ]]; then
    make_wrapper mrproper
fi

if [[ $* =~ "clean" ]]; then
    make_wrapper clean
fi

make_wrapper $DEFCONFIG || (echo "Failed to build with ${DEFCONFIG}, exiting!" &&
    exit 1)

START=$(date +"%s")
if [[ $* =~ "quiet" ]]; then
    make_wrapper |& ag -ia "error:|warning:"
else
    make_wrapper
fi
END=$(date +"%s")
DIFF=$((END - START))
echo -e "Build took $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds."

if [[ ! -f ${IMAGE} ]]; then
    echo -e "Build failed :P"
    exit 1
else
    echo -e "Build Succesful!"
fi
