name: 'Fetch Kernel'
description: 'Fetches the kernel from a target repository'

inputs:
  target_org:
    description: 'Target GitHub organization or user'
    required: true
  target_repo:
    description: 'Target repository name'
    required: true
  target_branch:
    description: 'Branch to fetch from'
    required: true

runs:
  using: "composite"
  steps:
    - name: Fetch Kernel Source
      shell: bash
      working-directory: /home/runner
      run: |
        mkdir android-kernel
        cd android-kernel
        git clone --depth=1 --branch "${{ inputs.target_branch }}" --single-branch \
          "https://github.com/${{ inputs.target_org }}/${{ inputs.target_repo }}.git" dandelion
        cd -
        cd android-kernel/dandelion
        pwd
        ls -la
        cd -
